###### This script is for automatically cleaning up general log files generated by MySQL ######
### Created in Ubuntu server ###
### This automation is intended for MySQL purposes ###

## Needs to enable general logging first ##
# /etc/mysql/mysql.conf.d -> nano mysqld.cnf

# From the config file: 
general_log = 1
log_output = FILE

# Create new file and save the below script
#!/bin/bash

# Define variables
SOURCE_FILE="" ### Depending on your general log default location
DEST_DIR="" ### Set destination path
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
BACKUP_FILE="$DEST_DIR/general_log_$TIMESTAMP.log"

# Ensure the backup directory exists
# mkdir -p "$DEST_DIR"

# Copy the general_log.csv to the backup location with a timestamp
cp "$SOURCE_FILE" "$BACKUP_FILE"

# Clear the contents of the original file after copying
cat /dev/null > "$SOURCE_FILE"

# Set proper ownership and permissions (ensure MySQL can continue writing logs)
# chown mysql:mysql "$SOURCE_FILE"
# chmod 640 "$SOURCE_FILE"

# Remove log files older than 5 days
find "$DEST_DIR" -type f -name "general_log_*.log" -mtime +5 -exec rm {} \;

echo "General_log.csv backup completed successfully: $BACKUP_FILE"
echo "Old log files older than 5 days have been removed."
##########

## Open crontab -e ##
#Schedule this job to run depending on your requirements
0 6 * * * <Script path> > <Destination Log Path>/cleanup_general_log.log 2>&1
